### ISSUE TITLE
Missing documentataion.

### ISSUE THREAD

**Issue by erlicthemad** [miyako/4d-plugin-qrencode-v2#1]
I noticed the post in the 4D forums about the plugin. And managed to get it working but Until I found that i had no idea how to use this plugin.

**Comment by miyako** [comment]
The repository is in project mode and the sample method is plain text.

https://github.com/miyako/4d-plugin-qrencode-v2/blob/master/qrencode/test/Project/Sources/Methods/TEST.4dm
