### ISSUE TITLE
I have this error in 4Dv17.5/64bits on Yosemite

### ISSUE THREAD

**Issue by olivierfaure** [miyako/4d-plugin-qrencode-v2#3]
4D v17 say error of license or privileges on Yosemite

**Comment by miyako** [comment]
the error means the plugin is not loaded. it has nothing to do with licenses or privileges.

if you run 

```
otool -l {the plugin executable file}
```

you will see

```
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform 1
    minos 10.15
      sdk 13.3
```
which mean it was compiled on Ventura and the minimum OS is Catalina.

you will also see that it contains 2 architectures, arm64 and x86_64.

**Comment by miyako** [comment]
the plugin needs to be recompiled on separate Macs and merged to support Intel Yosemite and ARM Big Sur.

if you need support for that, please contanct info-jp@4D.com for professional services.

**Comment by miyako** [comment]
alternatively, look for an earlier release, may the original plugin (not v2).

**Comment by miyako** [comment]
actually it looks like I can compile on Ventura and manually change the target to 10.10.

but I don't know if it works on Yosemite.

**Comment by miyako** [comment]
I will add to releases as 1.5.1

**Comment by olivierfaure** [comment]
Nice :)
