### ISSUE TITLE
Error loading plugin in client/server mac/pc

### ISSUE THREAD

**Issue by LaurenMassart** [miyako/4d-plugin-qrencode-v2#5]
Hello, in client/server engined in v20.3 with a windows server and a Mac client, the plugin does not work. Do you have a solution?

This causes the following error:

Error code: -9949 (4DRT)
License or privilege error. (qrencode (1.5.0))
component: '4DRT'
The executable could not be loaded.
task -8, name: 'Articles'

**Comment by miyako** [comment]
I have not tested myself, but maybe download the .dmg on a Mac, open it, then copy to Windows?

**Comment by LaurenMassart** [comment]
Yes !! that works !
Surprising that it didn't work with the zip...
Thank you very much and have a good day !
